/// Generic Dimensions
const MARGIN_SMALL = 4.0;
const MARGIN_MEDIUM = 8.0;
const MARGIN_MEDIUM_2 = 16.0;
const MARGIN_LARGE = 24.0;

const TEXT_REGULAR = 14.0;
const TEXT_REGULAR_2X = 16.0;
const TEXT_HEADING_1X = 24.0;

/// App Specific
const BANNER_SECTION_HEIGHT = 200.0;
const BANNER_PLAY_BUTTON_SIZE = 56.0;
const MOVIE_LIST_HEIGHT = 270.0;
const MOVIE_LIST_ITEM_WIDTH = 170.0;
