const MAIN_SCREEN_APP_BAR_TITLE = "Discover";
const MAIN_SCREEN_BEST_POPULAR_MOVIES_AND_SERIALS =
    "BEST POPULAR MOVIES AND SERIALS";
const SHOWCASES_TITLE = "SHOWCASES";
const SHOWCASES_SEE_MORE = "MORE SHOWCASES";
const BEST_ACTOR_TITLE = "BEST ACTORS";
const BEST_ACTOR_SEE_MORE = "MORE ACTORS";
const MAIN_SCREEN_CHECK_MOVIE_SHOWTIMES = "Check Movie\nShowtimes";
const MAIN_SCREEN_SEEMORE = "SEE MORE";

const MOVIE_DETAIL_SCREEN_ACOTRS_TITLE = "ACTORS";
const MOVIE_DETAIL_SCREEN_CREATORS_TITLE = "CREATORS";
const MOVIE_DETAIL_SCREEN_CREATORS_SEEMORE = "MORE CREATORS";
const MOVIE_DETAIL_SCREEN_STORYLINE_TITLE = "STORYLINE";
const MOVIE_DETAIL_SCREEN_RELATETD_MOVIES = "Related Movies";
