const MAIN_SCREEN_APP_BAR_TITLE = "Discover";
const MAIN_SCREEN_BEST_POPULAR_MOVIES_AND_SERIALS =
    "BEST POPULAR MOVIES AND SERIALS";
const SHOWCASES_TITLE = "SHOWCASES";
const SHOWCASES_SEE_MORE = "MORE SHOWCASES";
const BEST_ACTOR_TITLE = "BEST ACTORS";
const BEST_ACTOR_SEE_MORE = "MORE ACTORS";
