/// Hive Types
const int HIVE_TYPE_ID_ACTOR_VO = 1;
const int HIVE_TYPE_ID_COLLECTION_VO = 2;
const int HIVE_TYPE_ID_CREDIT_VO = 3;
const int HIVE_TYPE_ID_DATE_VO = 4;
const int HIVE_TYPE_ID_GENRE_VO = 5;
const int HIVE_TYPE_ID_MOVIE_VO = 6;
const int HIVE_TYPE_ID_PRODUCTION_COMPANY_VO = 7;
const int HIVE_TYPE_ID_PRODUCTION_COUNTRY_VO = 8;
const int HIVE_TYPE_ID_SPOKEN_LANGUAGE_VO = 9;

/// Hive Box Names
const String BOX_NAME_ACTOR_VO = "BOX_NAME_ACTOR_VO";
const String BOX_NAME_COLLECTION_VO = "BOX_NAME_COLLECTION_VO";
const String BOX_NAME_CREDIT_VO = "BOX_NAME_CREDIT_VO";
const String BOX_NAME_DATE_VO = "BOX_NAME_DATE_VO";
const String BOX_NAME_GENRE_VO = "BOX_NAME_GENRE_VO";
const String BOX_NAME_MOVIE_VO = "BOX_NAME_MOVIE_VO";
const String BOX_NAME_PRODUCTION_COMPANY_VO = "BOX_NAME_PRODUCTION_COMPANY_VO";
const String BOX_NAME_PRODUCTION_COUNTRY_VO = "BOX_NAME_PRODUCTION_COUNTRY_VO";
const String BOX_NAME_SPOKEN_LANGUAGE_VO = "BOX_NAME_SPOKEN_LANGUAGE_VO";
